version: '3.9'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/go/src/app
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - './frontend/dist:/app/dist'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  nginx:
    container_name: nginx_gateway
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./gateway
    volumes:
      - './frontend/dist:/app/dist'
    ports:
      - "5001:80"
